title: Yangadee Pages
logo: /assets/img/logo.png
description: Bring colors to life
show_downloads: false
github:
  is_project_page: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
mardown: kramdown
