lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
title: Yangadee Pages
description: Bring colors to life
show_downloads: true
google_analytics: true
github:
  is_project_page: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-architect
mardown: kramdown
