title: Yangadee Pages
description: Bring colors to life
show_downloads: true
github:
  is_project_page: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
mardown: kramdown
